name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t your-app-name .

      - name: Test Docker image
        run: |
          docker run -d --name test-container -p 8000:8000 your-app-name
          sleep 10  # Даем время для запуска сервера
          docker ps | grep test-container
          docker logs test-container
          # Проверяем, что сервер запустился
          docker exec test-container curl -s http://localhost:8000 | grep -q "some-expected-response" || exit 1
          docker stop test-container
          docker rm test-container