name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Проверка HTML
    - name: Validate HTML
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
        npm install -g html-validate
        html-validate src/index.html

    # Проверка Python (если есть бэкенд)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python tests
      run: |
        python -m pytest tests/ || echo "No tests found"